# Generated by Django 5.0.2 on 2024-02-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('operating_hours', models.TextField()),
                ('waze_link', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
